// <auto-generated />
using System;
using DAL_EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL_EF.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20180716194218_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL_EF.Models.Aircrafts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Aid");

                    b.Property<DateTime>("AircraftBuildDate");

                    b.Property<long>("AircraftExpluatationSpan");

                    b.Property<string>("AircraftName");

                    b.Property<int?>("AircraftsModelsId");

                    b.HasKey("Id");

                    b.HasIndex("AircraftsModelsId");

                    b.ToTable("AircraftsList");
                });

            modelBuilder.Entity("DAL_EF.Models.AircraftsModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AMid");

                    b.Property<int>("AircraftTonnage");

                    b.Property<string>("ModelName");

                    b.Property<int>("PlacesCount");

                    b.HasKey("Id");

                    b.ToTable("AircraftsModelsList");
                });

            modelBuilder.Entity("DAL_EF.Models.Crews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cid");

                    b.Property<int?>("PilotId");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("CrewsList");
                });

            modelBuilder.Entity("DAL_EF.Models.Departures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftId");

                    b.Property<int?>("CrewId");

                    b.Property<DateTime>("DepartureDate");

                    b.Property<int>("Did");

                    b.Property<int?>("FlightId");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("CrewId");

                    b.HasIndex("FlightId");

                    b.ToTable("DeparturesList");
                });

            modelBuilder.Entity("DAL_EF.Models.Flights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PointOfDepartures");

                    b.Property<string>("PointOfDestination");

                    b.Property<DateTime>("TimeOfArrival");

                    b.Property<DateTime>("TimeOfDeparture");

                    b.HasKey("Id");

                    b.ToTable("FlightsList");
                });

            modelBuilder.Entity("DAL_EF.Models.Pilots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<int>("Experience");

                    b.Property<string>("Name");

                    b.Property<int>("Pid");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("PilotsList");
                });

            modelBuilder.Entity("DAL_EF.Models.Stewardesses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CrewsId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Name");

                    b.Property<int>("Sid");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("CrewsId");

                    b.ToTable("StewardessesList");
                });

            modelBuilder.Entity("DAL_EF.Models.Tickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftsId");

                    b.Property<int?>("FlihtID");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.HasIndex("AircraftsId");

                    b.HasIndex("FlihtID");

                    b.ToTable("TicketsList");
                });

            modelBuilder.Entity("DAL_EF.Models.Aircrafts", b =>
                {
                    b.HasOne("DAL_EF.Models.AircraftsModels", "AircraftsModels")
                        .WithMany()
                        .HasForeignKey("AircraftsModelsId");
                });

            modelBuilder.Entity("DAL_EF.Models.Crews", b =>
                {
                    b.HasOne("DAL_EF.Models.Pilots", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId");
                });

            modelBuilder.Entity("DAL_EF.Models.Departures", b =>
                {
                    b.HasOne("DAL_EF.Models.Aircrafts", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("DAL_EF.Models.Crews", "Crew")
                        .WithMany()
                        .HasForeignKey("CrewId");

                    b.HasOne("DAL_EF.Models.Flights", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");
                });

            modelBuilder.Entity("DAL_EF.Models.Stewardesses", b =>
                {
                    b.HasOne("DAL_EF.Models.Crews")
                        .WithMany("StewardessList")
                        .HasForeignKey("CrewsId");
                });

            modelBuilder.Entity("DAL_EF.Models.Tickets", b =>
                {
                    b.HasOne("DAL_EF.Models.Aircrafts")
                        .WithMany("Tickets")
                        .HasForeignKey("AircraftsId");

                    b.HasOne("DAL_EF.Models.Flights", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlihtID");
                });
#pragma warning restore 612, 618
        }
    }
}
